PrimeIntellect-ai/protocol

.gitignore, .tmuxinator.yml, Makefile, README.md
- Readme improvements
- Use modern docker command
- Ignore all .pem keys
=> Readme improvements

dev-utils/examples/invalidate_work.rs, dev-utils/examples/submit_work.rs, validator/Dockerfile, validator/src/main.rs
You can now disable the hw validation on the validator to e.g. have multiple validators - one for each compute pool
=> Improvement: ability to disable hw validation

worker/src/checks/software/docker.rs
We must ensure we actually have access with our current user to the docker env
=> Fix: permission detection

worker/src/docker/docker_manager.rs
saw multiple tasks where the task folder was not properly removed
=> Improve Container & task folder removal

worker/scripts/install.sh
Check if docker is properly configured when setting up prime-worker
=> add docker check in install check

Makefile, deployment/k8s/orchestrator-chart/templates/orchestrator-deployment.yaml, orchestrator/Dockerfile, orchestrator/src/api/routes/storage.rs, orchestrator/src/api/server.rs, orchestrator/src/api/tests/helper.rs, orchestrator/src/main.rs
=> Feature: s3 upload ratelimiter

orchestrator/src/api/routes/heartbeat.rs, orchestrator/src/api/routes/nodes.rs, orchestrator/src/node/invite.rs, orchestrator/src/node/status_update.rs, shared/src/models/challenge.rs, shared/src/models/heartbeat.rs, shared/src/models/invite.rs, shared/src/security/auth_signature_middleware.rs, validator/src/main.rs, validator/src/validators/hardware_challenge.rs, worker/src/api/routes/invite.rs, worker/src/operations/heartbeat/service.rs, worker/src/services/discovery.rs
=> Improvements: Worker stability & security

.github/workflows/checks.yml
=> reactivate tests

Cargo.lock, Cargo.toml, Makefile, crates/shared/src/models/node.rs, crates/worker/Cargo.toml, crates/worker/src/checks/mod.rs, crates/worker/src/checks/stun.rs, crates/worker/src/cli/command.rs, crates/worker/src/docker/docker_manager.rs, crates/worker/src/utils/logging.rs
=> Feature: stun based ip detection

Makefile, crates/orchestrator/Dockerfile, crates/orchestrator/src/api/routes/storage.rs, crates/orchestrator/src/api/tests/helper.rs, crates/orchestrator/src/main.rs, crates/orchestrator/src/models/node.rs, crates/orchestrator/src/plugins/node_groups/mod.rs, crates/orchestrator/src/plugins/node_groups/scheduler_impl.rs, crates/orchestrator/src/plugins/node_groups/tests.rs, crates/shared/src/models/mod.rs, crates/shared/src/models/storage.rs, crates/shared/src/models/task.rs, crates/shared/src/utils/google_cloud.rs, crates/validator/Dockerfile, crates/validator/src/main.rs, crates/worker/src/docker/service.rs, crates/worker/src/docker/taskbridge/file_handler.rs
A task can now include a storage configuration to define how a file is named and uploaded.
=> Feature: task storage configuration

.tmuxinator.yml
=> move setup to tmuxinator project start command to remove sleeps

crates/worker/src/docker/docker_manager.rs
=> set appropriate permissions for docker shared folders

crates/worker/src/docker/taskbridge/bridge.rs
=> Adjust socket path permissions for system wide writes

crates/validator/Cargo.toml, crates/validator/src/metrics.rs, crates/validator/src/validators/synthetic_data/mod.rs
move validator to async redis, remove unwraps, add work units check
=> Group Work Unit checks

crates/dev-utils/examples/test_concurrent_calls.rs, crates/shared/src/web3/contracts/helpers/utils.rs, crates/worker/src/api/routes/invite.rs, crates/worker/src/docker/taskbridge/file_handler.rs
=> adjust file submission and retry logic

crates/orchestrator/src/api/routes/heartbeat.rs, crates/orchestrator/src/main.rs, crates/orchestrator/src/metrics/mod.rs, crates/orchestrator/src/metrics/sync_service.rs
=> Fix: stale metrics in distributed deployment of orchestrator

Cargo.lock, crates/discovery/Cargo.toml, crates/discovery/src/api/routes/get_nodes.rs, crates/discovery/src/api/routes/node.rs, crates/discovery/src/chainsync/sync.rs, crates/discovery/src/main.rs, crates/discovery/src/store/node_store.rs
=> make discovery service async, optimize redis performance

crates/worker/src/cli/command.rs
improve error message when firewall blocks the discovery upload
=> add explicit logging when fw blocks discovery upload

crates/orchestrator/src/plugins/node_groups/scheduler_impl.rs, crates/orchestrator/src/plugins/node_groups/tests.rs, crates/orchestrator/src/scheduler/mod.rs, crates/shared/src/models/task.rs, crates/worker/src/docker/docker_manager.rs, crates/worker/src/docker/service.rs
fixes #446
```
{
"image": "primeintellect/prime-rl:main",
"cmd": [
"@configs/...",
"--dataset", "xyz
],
"entrypoint": null  // optional: override image's ENTRYPOINT
}
```
=> imp(orchestrator): improve task creation api

crates/discovery/src/api/routes/node.rs, crates/orchestrator/src/discovery/monitor.rs, crates/shared/src/models/node.rs, crates/worker/src/checks/hardware/hardware_check.rs, crates/worker/src/checks/hardware/mod.rs, crates/worker/src/checks/hardware/storage.rs, crates/worker/src/checks/hardware/storage_path.rs, crates/worker/src/cli/command.rs, crates/worker/src/docker/docker_manager.rs, crates/worker/src/docker/service.rs, crates/worker/src/docker/taskbridge/bridge.rs
=> feat(worker): ability to manually set storage path

crates/worker/src/docker/service.rs
=> add ability to customize the socket path env var

Makefile, crates/discovery/Dockerfile, crates/discovery/src/api/routes/get_nodes.rs, crates/discovery/src/api/routes/node.rs, crates/discovery/src/api/server.rs, crates/discovery/src/main.rs, crates/discovery/src/store/node_store.rs, crates/orchestrator/Dockerfile, deployment/k8s/orchestrator-chart/templates/orchestrator-deployment.yaml, deployment/k8s/orchestrator-chart/values.example.yaml, docker-compose.yml
=> allow to set threshold of same ips per discovery node

.env.example, Makefile, crates/orchestrator/src/discovery/monitor.rs, crates/orchestrator/src/main.rs, crates/validator/src/main.rs, crates/worker/src/cli/command.rs, crates/worker/src/services/discovery.rs, deployment/k8s/orchestrator-chart/templates/orchestrator-deployment.yaml, deployment/k8s/orchestrator-chart/values.example.yaml, deployment/k8s/validator-chart/templates/validator-deployment.yaml, deployment/k8s/validator-chart/values.example.yaml, docker-compose.yml
=> feat: allow loading data from multiple disc svc

Makefile, crates/dev-utils/examples/transfer_eth.rs, crates/discovery/Dockerfile, crates/discovery/src/api/routes/get_nodes.rs, crates/discovery/src/api/routes/node.rs, crates/discovery/src/api/server.rs, crates/discovery/src/main.rs
=> feat: support multiple discovery pods

deployment/k8s/discovery-chart/templates/secret.yaml, deployment/k8s/orchestrator-chart/templates/_helpers.tpl, deployment/k8s/orchestrator-chart/templates/processor-deployment.yaml
- **fix orchestrator validation**
- **discovery: match existing secrets name**
=> fix helm chart

Cargo.toml, crates/discovery/Cargo.toml, crates/discovery/src/api/mod.rs, crates/discovery/src/api/routes/get_nodes.rs, crates/discovery/src/api/routes/mod.rs, crates/discovery/src/api/routes/node.rs, crates/discovery/src/api/server.rs, crates/discovery/src/lib.rs, crates/discovery/src/main.rs, crates/discovery/src/store/mod.rs
=> fix `unreachable_pub` for discovery
