- discovery/src/api/routes/get_nodes.rs
Discovery service sends 503 and panicks instead of sending a 404 when you request a pool id that does not exist.
> Fix: discovery wrong status on missing pool

- Makefile
- discovery/Dockerfile
- discovery/src/api/server.rs
- discovery/src/main.rs
- docker-compose.yml
- shared/src/web3/contracts/implementations/prime_network_contract.rs
- worker/src/api/server.rs
- worker/src/cli/command.rs
> load validator addresses from contract

- worker/src/cli/command.rs
> add discovery upload retries

- orchestrator/src/node/status_update.rs
This fixes an ugly orchestrator edge case that can happen when the orchestrator is down for a while but invites nodes before going under. 
Orchestrator invites nodes > Nodes are still in discovered, keeps inviting while nodes are already in pool.
> fix orchestrator discovered edgecase

- validator/src/main.rs
Sometimes the validator got stuck in the past (which we def. have to fix) but this way K8s simply restarts the validator if it does not validate properly.
> Improvement: validator health loop link

- orchestrator/src/node/invite.rs
- orchestrator/src/node/status_update.rs
A node can be stuck in waiting for heartbeat without ever sending an HB. This PR fixes this edge case.
> fix edge case where node is stuck in waiting for heartbeat

- worker/src/docker/taskbridge/file_handler.rs
> handle double work submission error due to latency

- discovery/src/api/routes/get_nodes.rs
- discovery/src/api/routes/node.rs
- discovery/src/api/server.rs
- discovery/src/chainsync/sync.rs
- discovery/src/main.rs
> Improvement: Discovery heartbeat based on chainsync

- Makefile
- worker/src/operations/provider.rs
> Fix: eth balance display

- worker/src/checks/issue.rs
- worker/src/checks/software/mod.rs
- worker/src/checks/software/port.rs
- worker/src/checks/software/software_check.rs
- worker/src/cli/command.rs
- worker/src/docker/service.rs
Fixes https://github.com/PrimeIntellect-ai/protocol/issues/63
> Add software check for miner port

- Cargo.lock
- Cargo.toml
- dev-utils/Cargo.toml
- discovery/Cargo.toml
- orchestrator/Cargo.toml
- shared/Cargo.toml
- validator/Cargo.toml
- worker/Cargo.toml
Hi all, first PR around here, tackling some of the low hanging fruit. 
Leaving it on draft in case there's any preliminary reviews before I get the full env working and fully run cargo test (granted it does compile and that is mostly what is relevant for this pr). Clippy and fmt applied.
- Solves #99
> Refactor: use shared dependencies across crates

- worker/src/docker/service.rs
Addresses https://github.com/PrimeIntellect-ai/protocol/issues/60
> improvement: exp backoff for container on failure

- orchestrator/src/main.rs
> add check if pool is active

- crates/worker/src/cli/command.rs
- crates/worker/src/services/discovery.rs
- crates/worker/src/services/discovery_updater.rs
- crates/worker/src/services/mod.rs
- crates/worker/src/state/system_state.rs
The discovery updater runs regularly while the node is not part of a pool. This increases resilience since the orchestrator always compares date of death with change on discovery svc.
> Feature: discovery updater

- crates/orchestrator/src/api/routes/heartbeat.rs
- crates/orchestrator/src/api/routes/task.rs
- crates/orchestrator/src/store/domains/task_store.rs
- crates/shared/src/models/task.rs
- crates/worker/src/docker/service.rs
keep all tasks in orchestrator store, add get_all functionality, change route from /tasks to /tasks/current to get the running task
> Orchestrator: Keep old tasks in store

- crates/orchestrator/Dockerfile
- crates/orchestrator/src/api/server.rs
- crates/orchestrator/src/api/tests/helper.rs
- crates/orchestrator/src/discovery/monitor.rs
- crates/orchestrator/src/main.rs
- crates/orchestrator/src/node/status_update.rs
- crates/orchestrator/src/utils/loop_heartbeats.rs
- deployment/k8s/orchestrator-chart/templates/orchestrator-deployment.yaml
- deployment/k8s/orchestrator-chart/values.example.yaml
We introduce new server modes to enable / disable the processing of nodes on the orchestrator. 
This way we can have autoscaling around the API while having one processor. K8s handles the rest.  
fixes #19
> introduce server modes to improve scalability of svc

- .env.example
- Makefile
- crates/validator/Dockerfile
- crates/validator/src/main.rs
- crates/validator/src/validators/synthetic_data.rs
- deployment/k8s/validator-chart/templates/secret.yaml
- deployment/k8s/validator-chart/templates/validator-deployment.yaml
- deployment/k8s/validator-chart/values.example.yaml
Previously a validator was connected to a single toploc server. Now we want to support validating multiple models hence have to support multiple toploc servers. 
You can simply pass in a configuration of toploc servers now that use filename prefix matching to route the files to the correct server: 
```
TOPLOC_CONFIGS="[{\"server_url\":\"http://localhost:8080\",\"auth_token\":\"token\", \"file_prefix_filter\":\"model_name\"}]"
```
> Support multiple toploc servers in synthetic-data validation

- .env.example
- Cargo.lock
- Cargo.toml
- crates/orchestrator/Cargo.toml
- crates/orchestrator/Dockerfile
- crates/orchestrator/src/api/routes/storage.rs
- crates/orchestrator/src/api/tests/helper.rs
- crates/orchestrator/src/events/mod.rs
- crates/orchestrator/src/main.rs
- crates/orchestrator/src/metrics/mod.rs
- crates/orchestrator/src/metrics/webhook_sender.rs
- crates/orchestrator/src/plugins/node_groups/mod.rs
- crates/orchestrator/src/plugins/node_groups/tests.rs
- crates/orchestrator/src/plugins/webhook/mod.rs
- crates/orchestrator/src/store/domains/metrics_store.rs
- crates/validator/Cargo.toml
- deployment/k8s/orchestrator-chart/templates/orchestrator-deployment.yaml
- deployment/k8s/orchestrator-chart/values.example.yaml
This feature introduces a more advanced webhook plugin that automatically sends events for node status changes, groups and metrics. Metrics are simply sent periodically if changes on the aggregated metrics are detected. 
For testing I've simply used `https://webhook.site`, added this to my env: `WEBHOOK_CONFIGS='[{"url": "https://webhook.site/<your code>}]'` and started the setup using `make up`. After adding a worker I can see events pop in. To test the metrics I simply used the bridge in the /examples folder. Make sure to create a task & adjust the task_id. 
Event Examples:
```
{
"event": "metrics.updated",
"data": {
"gpu_0_utilization": 67,
"gpu_3_memory_total": 85899345920,
"gpu_2_memory_used": 76715130880,
"gpu_3_utilization": 91,
"memory_usage": 1432368,
},
"timestamp": …
```
> Feature: Advanced Webhooks

- crates/orchestrator/src/api/routes/heartbeat.rs
- crates/orchestrator/src/api/routes/storage.rs
- crates/orchestrator/src/main.rs
- crates/orchestrator/src/metrics/mod.rs
- crates/orchestrator/src/metrics/sync_service.rs
- crates/orchestrator/src/status_update/mod.rs
- adds additional metrics to orchestrator operations (e.g. file upload count, tasks, nodes in different states etc.) 
- adds file name to task metrics that are sent by remote nodes
fixes #411
> add additional prometheus operator metrics, add taskname to node metrics

- .github/workflows/dev-release.yml
- crates/worker/build.rs
- crates/worker/src/cli/command.rs
- crates/worker/src/operations/heartbeat/service.rs
Currently in dev releases the wrong worker version is reported which makes large scale integration tests hard.
> Include exact version tag in dev-release

- crates/worker/src/docker/taskbridge/bridge.rs
> fix(worker): do not submit work when work units are 0

- crates/orchestrator/src/discovery/monitor.rs
- crates/orchestrator/src/store/domains/heartbeat_store.rs
- crates/shared/src/security/auth_signature_middleware.rs
- crates/worker/src/operations/heartbeat/service.rs
This PR includes small improvements to logs that we're seeing on our testnet run.
Primarily nothing critical, just a way to get rid of some logs.
> imp(general): Orchestrator Discovery Sync, Worker Timeouts

- crates/dev-utils/examples/submit_work.rs
- crates/discovery/src/chainsync/sync.rs
- crates/discovery/src/main.rs
- crates/orchestrator/src/metrics/webhook_sender.rs
- crates/orchestrator/src/plugins/node_groups/mod.rs
- crates/orchestrator/src/plugins/webhook/mod.rs
- crates/orchestrator/src/status_update/mod.rs
- crates/shared/src/web3/contracts/implementations/compute_pool_contract.rs
- crates/validator/src/validators/synthetic_data/chain_operations.rs
- crates/validator/src/validators/synthetic_data/mod.rs
- crates/validator/src/validators/synthetic_data/tests/mod.rs
- crates/worker/src/cli/command.rs
- crates/worker/src/docker/taskbridge/bridge.rs
- crates/worker/src/docker/taskbridge/file_handler.rs
- crates/worker/src/p2p/service.rs
fix clippy's `unused_async` warnings by removing unused async from functions and refactoring into test-specific functions if necessary.
i'm not a huge fan of the changes in `crates/validator/src/validators/synthetic_data/chain_operations.rs`, but this will likely involve larger test refactors to remove all the `#[cfg]`s, which i can tackle later.
> refactor: remove unused async from functions

- crates/shared/src/web3/contracts/helpers/utils.rs
- increase the pending transaction timeout from 30s to 60s.
- also check if the tx was included after the retry loop `sleep`, in which case, return
- based on the chain of errors logs, it appeared the pending transaction was timing out after 30s, so it was then retried with `Retrying with bumped fees...`, however the tx was included in between the time it timed out and when the retry was started, so the second submission failed
closes #597
closes #596
> fix: increase pending transaction timeout

- Cargo.lock
- crates/worker/Cargo.toml
- crates/worker/src/cli/command.rs
- crates/worker/src/docker/taskbridge/bridge.rs
- examples/python/taskbridge_basic.py
- change the default task bridge socket file to be in the user's home directory
- previously it was in `/tmp`, which is cleared on restart. the container persists on reboot and it tries to recreate the dir since it no longer exists but w root perms, which is not writable by the worker running as a user
- it's now in the user `prime-worker` directory which is persistent
> fix: change default task bridge socket file to be in home dir

- Cargo.toml
- crates/validator/Cargo.toml
- crates/validator/src/lib.rs
- crates/validator/src/main.rs
- crates/validator/src/p2p/mod.rs
- crates/validator/src/store/mod.rs
- crates/validator/src/validators/hardware_challenge.rs
- crates/validator/src/validators/mod.rs
- crates/validator/src/validators/synthetic_data/mod.rs
- crates/validator/src/validators/synthetic_data/toploc.rs
- crates/validator/src/validators/synthetic_data/types.rs
part of https://github.com/PrimeIntellect-ai/protocol/issues/604; add the `unreachable_pub` lint to the validator crate and auto-apply the fixes.
> fix `unreachable_pub` for validator crate
